version: "3"

services:
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"
  api:
    restart: always
    container_name: hermes
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PORT=8000
      - QUEUE=published_message
      - MONGO_URI=mongodb://mongo:27017/hermes
      - NODE_ENV=development

    links:
      - mongo
      - rabbitmq

    depends_on:
      - mongo

    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "8000:8000"
